### ISSUE TITLE
Slider randomly doesn't show up on MacOS

### ISSUE THREAD

**Issue by 1valdis** [JohnEdChristensen/WebbCompare#11]
Works fine on Windows. On MacOS, on some pictures the slider will show up, on some it won't and instead looks like a picture without any interactivity:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/18512697/178692838-590b06e8-eda6-4749-92a0-f77727ce8969.png">
Chrome 103 MacOS 12.3.

**Comment by Pranjalmishra30** [comment]
Got the same issue in Ubuntu 20.04. Also one of the images has only half of the slider. Attaching the images for reference. Tested on chrome and firefox


![Screenshot from 2022-07-13 14-44-34](https://user-images.githubusercontent.com/55613727/178697673-0d1de594-939f-459f-a4d1-03e29e01c4ef.png)

![Screenshot from 2022-07-13 14-44-50](https://user-images.githubusercontent.com/55613727/178698048-fbb3b3f5-387c-4d1d-b98d-981cdbae0240.png)

**Comment by 1valdis** [comment]
@Pranjalmishra30 the second one is by design: Hubble's photo doesn't cover the bottom area unlike Webb's one. Maybe less confusing would be to cut away the bottom part which Hubble doesn't have covered.

**Comment by Pranjalmishra30** [comment]
Okk i didn't know that. Also the slider not showing up was just a one time issue. It works now

**Comment by jmona789** [comment]
Works for me on MacOS

**Comment by JohnEdChristensen** [comment]
I'm no longer using this slider control, so this should be resolved.
