### ISSUE TITLE
Sliders doesn't work correct with changed window size

### ISSUE THREAD

**Issue by mbiesiad** [JohnEdChristensen/WebbCompare#15]
Hi. First of all, really great project & idea! I love this!

# Repro steps
1. Go to: https://johnedchristensen.github.io/WebbCompare/
2. Change browser window size to smaller (and finally to the smallest width)
3. See that sliders behavior is incorrect (jumpy or stuck)

# Additional context
It's quite similar & perhaps related with issue #7 But in this case, the issue occurs just after changing browser' window size (smaller values than default).
Browser: Firefox as well as Chrome

Best wishes,

**Comment by JohnEdChristensen** [comment]
Zooming in should be much more reliable now.
