### ISSUE TITLE
Add comparison of Jupiter

### ISSUE THREAD

**Issue by LifeIsStrange** [JohnEdChristensen/WebbCompare#19]
James Webb:
https://www.reddit.com/r/jameswebb/comments/vzbrqg/comment/ig944ro/?utm_medium=android_app&utm_source=share&context=3

Hubble : https://www.nasa.gov/sites/default/files/thumbnails/image/stsci-h-p2042a-f-1663x1663.png
https://www.nasa.gov/feature/goddard/2020/hubble-captures-crisp-new-portrait-of-jupiters-storms

**Comment by JohnEdChristensen** [comment]
Thanks for submitting an issue! I don't' think the target audience for this site (the general public, not necessarily very familiar with astronomy) would understand why these two images are so different. 

I'd love to add some comparisons that clearly show that Webb "sees" using near/mid infrared, but I don't think these images very clearly illustrate that.
