### ISSUE TITLE
There should be clear guidelines on how to contribute

### ISSUE THREAD

**Issue by jculpon** [JohnEdChristensen/WebbCompare#20]
Nice to have: A clear CONTRIBUTING and CONTRIBUTORS file (jculpon can provide some examples) along with a code of content to make it clear (beyond people familiar with working with GPLv3) how to contribute to the repository (and be credited if desired).

It’s probably fine to have most of this in README.md at this stage, but this tool is likely to be passed around for a while in an education context in addition to the scientific one, so it’s good to have “teacher-friendly” or “not GPL programming” instructions in case students find issues they think should be fix during lectures.

**Comment by mbiesiad** [comment]
It would be also nice to have a (1) short descr. about how-to launch on a local environm. and (2) branching policy explanation (at this moment `main` branch was updated 6 days ago).

Best wishes,

**Comment by jculpon** [comment]
@mbiesiad I agree, but as I am not the primary author on this repository, I’ve been trying to take care of that via the Punch Elvis Organization as it’s ```Sabbatical season``` here in Arizona. Maybe the best way to hash this out is to discuss this on my fork over on that org, rather than bothering the primary author before this gets added to ports/portage? (Apologies for terms, I speak BSD / NetBSD more often than GNU/Debian or Ubuntu these days.)

**Comment by JohnEdChristensen** [comment]
Added a CONTRIBUTING.md file. Let me know if there is anything else I should add or if you have anymore questions!

**Comment by jculpon** [comment]
Not reopening: I'll rebase on your contributing, but I had been setting up that plus DEPENDABOT plus a Code of Conduct on punchelvis/WebbCompare. I'll send a PR unless contraindicated.
