### ISSUE TITLE
new official image of Cartwheel Galaxy

### ISSUE THREAD

**Issue by ryran** [JohnEdChristensen/WebbCompare#25]
https://www.nasa.gov/feature/goddard/2022/webb-captures-stellar-gymnastics-in-the-cartwheel-galaxy

https://www.nasa.gov/image-feature/goddard/2018/hubble-s-cartwheel

**Comment by JohnEdChristensen** [comment]
Just added this.

**Comment by ryran** [comment]
You rock! It's beautiful!
