### ISSUE TITLE
[BUG] Slider bug on Carina Nebula only

### ISSUE THREAD

**Issue by zateutsch** [JohnEdChristensen/WebbCompare#5]
Slider is a bit wonky and doesn't fully pane between the two images:

![image](https://user-images.githubusercontent.com/88554871/178595360-2027b8ff-2b0c-4c14-814e-3ba6e35e4568.png)

**Comment by zateutsch** [comment]
This bug occurred both on Edge for desktop, and Safari for mobile. Didn't test in any other browsers.

**Comment by andrew-welch** [comment]
The Hubble image is actually smaller so not doing a full comparison.

See: https://hubblesite.org/contents/media/images/2008/34/2405-Image.html?itemsPerPage=100&keyword=Carina

**Comment by phord** [comment]
No slider at all appears on my browser (Brave/Chromium on Linux) for the Carina Nebula.
![image](https://user-images.githubusercontent.com/123908/178607422-716df40f-529e-4e2b-bd8c-291f96a55ff9.png)

Also, if I zoom in on my browser, all the sliders get stuck on the far left, as if their range is [0, 0].

**Comment by JohnEdChristensen** [comment]
Should be fixed now thanks to PR https://github.com/JohnEdChristensen/WebbCompare/pull/2
