### ISSUE TITLE
Slider doesn't work quite right when zoomed in on webpage

### ISSUE THREAD

**Issue by xconverge** [JohnEdChristensen/WebbCompare#7]
I have a high res monitor so I zoomed in my browser window to 160% and the cursor position math seems to be a bit wonky and jumpy as you try to adjust the slider

**Comment by xconverge** [comment]
The slider component used in the live demo does not have the same issue, so I think this is a integration issue of the component and not the library/component itself https://codyhouse.co/ds/components/app/accessible-img-compare-slider

**Comment by phord** [comment]
When I zoom in to 110% on Brave/Chromium on Linux, all the sliders get stuck on the left side.

**Comment by xconverge** [comment]
> When I zoom in to 110% on Brave/Chromium on Linux, all the sliders get stuck on the left side.

For me they dont get "stuck" they snap to the left side but then moving the mouse (even though the cursor is in a way different place than the drag icon) still does somewhat work, I just run out of screen real estate to slide

**Comment by JohnEdChristensen** [comment]
A workaround is to refresh the page after zooming in. Not sure what the best way to fix this right now. Adding proper zoom support for each image would probably make the most sense.

**Comment by mbiesiad** [comment]
Quite short notes from me here - (1) If you zoom in and refresh the page - the sliders disappear.
(2) In general zoom out works fine for me, but with some values the issue also occurs (the same as described).

**Comment by jmona789** [comment]
If you're on chrome on a macbook, you can also pinch to Zoom on with the trackpad and the slider works fine doing it thst way

**Comment by JohnEdChristensen** [comment]
Zooming in should be much more intuitive and reliable now. You can even go fullscreen!
