### ISSUE TITLE
Mobile view issue

### ISSUE THREAD

**Issue by erich-hs** [JohnEdChristensen/WebbCompare#8]
The slider doesn't appear on mobile view for the Carina Nebula. Apparently I can trigger it to appear by going landscape mode. Brave desktop works just fine.
![Screenshot_20220712-153243_Brave](https://user-images.githubusercontent.com/77303576/178609473-29de9d2f-5979-4165-ac5b-e082a1ff424a.jpg)

**Comment by JohnEdChristensen** [comment]
Should be fixed now thanks to PR https://github.com/JohnEdChristensen/WebbCompare/pull/2
