### ISSUE TITLE
`cd-image-container` `max-width` hinders experience on large screens

### ISSUE THREAD

**Issue by josiah-roberts** [JohnEdChristensen/WebbCompare#9]
The maximum size this site will show images at is 768px wide. That's very small on a desktop monitor. Would be much better if on desktop form-factor we could use more screen real-estate.

The mitigation for this right now is to zoom the whole page, but then the slider breaks.

**Comment by JohnEdChristensen** [comment]
I just released an update that makes zooming in and panning around possible. You can even go full screen to get 100% screen real-estate!
